# Generated by Django 5.1.6 on 2025-03-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_name_person_first_name_person_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_checked_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='last_checkin_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='last_checkout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
