# Generated by Django 5.1.6 on 2025-03-16 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_person_is_checked_in_person_last_checkin_time_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='AdA',
        ),
        migrations.DeleteModel(
            name='CheckInOut',
        ),
    ]
