# Generated by Django 5.1.6 on 2025-03-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_person_ada_delete_checkinout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ada',
            name='nfc_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
