# Generated by Django 5.1.6 on 2025-03-16 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_ada_nfc_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFCChip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nfc_id', models.CharField(max_length=50, unique=True)),
                ('ada', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nfc_chip', to='core.ada')),
            ],
        ),
    ]
