# Generated by Django 5.1.6 on 2025-03-16 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_nfcchip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ada',
            name='nfc_id',
        ),
    ]
