# Generated by Django 5.1.7 on 2025-03-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_ada_nfc_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ada',
            name='rank',
            field=models.CharField(choices=[('Sdt', 'Soldat (Sdt)'), ('Gfr', 'Gefreiter (Gfr)'), ('Obgfr', 'Obergefreiter (Obgfr)'), ('Kpl', 'Korporal (Kpl)'), ('Wm', 'Wachtmeister (Wm)'), ('Obwm', 'Oberwachtmeister (Obwm)'), ('Fw', 'Feldweibel (Fw)'), ('Four', 'Fourier (Four)'), ('Hptfw', 'Hauptfeldweibel (Hptfw)'), ('Adj Uof', 'Adjutant Unteroffizier (Adj Uof)'), ('Stabsadj', 'Stabsadjutant (Stabsadj)'), ('Hptadj', 'Hauptadjutant (Hptadj)'), ('Chefadj', 'Chefadjutant (Chefadj)'), ('Lt', 'Leutnant (Lt)'), ('Oblt', 'Oberleutnant (Oblt)'), ('Hptm', 'Hauptmann (Hptm)'), ('Maj', 'Major (Maj)'), ('Oberstlt', 'Oberstleutnant (Oberstlt)'), ('Oberst', 'Oberst'), ('Fach Of', 'Fachoffizier (Fach Of)'), ('Br', 'Brigadier (Br)'), ('Div', 'Divisionär (Div)'), ('KKdt', 'Korpskommandant (KKdt)'), ('Gen', 'General')], max_length=20),
        ),
    ]
